# Generated by Django 5.0.3 on 2024-04-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='this is the default message')),
                ('annonuser', models.TextField(default='*user*')),
                ('created_at', models.TextField(default='0000-00-00')),
            ],
        ),
    ]
